package com.toolsfordevs.fast.modules.resourcepicker.color

import android.content.Context
import android.graphics.Color
import com.toolsfordevs.fast.core.util.ResUtils
import com.toolsfordevs.fast.modules.resourcepicker.*
import com.toolsfordevs.fast.modules.resources.ColorResource


internal class MaterialColorPicker(context:Context) : ResourcePickerView(context)
{
    private var viewDelegate: ColorViewDelegate
    private var listener:((ColorResource)->Unit)? = null

    init {

        val colorButton = addButton(R.drawable.fast_resourcepicker_ic_palette)
        val filterButton = addButton(R.drawable.fast_resourcepicker_ic_filter)
        val viewButton = addButton(R.drawable.fast_resourcepicker_ic_view_list)

        viewDelegate = ColorViewDelegate(viewButton, recyclerView, Prefs::materialColorPickerMode) { color -> listener?.invoke(color) }
        viewDelegate.setSpanCount(4)

        val backgroundColorDelegate = BackgroundColorDelegate(colorButton) { color -> viewDelegate.setColorTheme(color) }

        viewDelegate.setColorTheme(Color.WHITE)

        val data = arrayListOf<ColorResource>()

        data.add(ColorResource("Black_12", R.color.fast_md_black_12, ResUtils.getColor(R.color.fast_md_black_12)))
        data.add(ColorResource("Black_38", R.color.fast_md_black_38, ResUtils.getColor(R.color.fast_md_black_38)))
        data.add(ColorResource("Black_50", R.color.fast_md_black_50, ResUtils.getColor(R.color.fast_md_black_50)))
        data.add(ColorResource("Black_54", R.color.fast_md_black_54, ResUtils.getColor(R.color.fast_md_black_54)))
        data.add(ColorResource("Black_87", R.color.fast_md_black_87, ResUtils.getColor(R.color.fast_md_black_87)))
        data.add(ColorResource("Black_100", R.color.fast_md_black_100, ResUtils.getColor(R.color.fast_md_black_100)))
        data.add(ColorResource("White_12", R.color.fast_md_white_12, ResUtils.getColor(R.color.fast_md_white_12)))
        data.add(ColorResource("White_38", R.color.fast_md_white_38, ResUtils.getColor(R.color.fast_md_white_38)))
        data.add(ColorResource("White_50", R.color.fast_md_white_50, ResUtils.getColor(R.color.fast_md_white_50)))
        data.add(ColorResource("White_54", R.color.fast_md_white_54, ResUtils.getColor(R.color.fast_md_white_54)))
        data.add(ColorResource("White_87", R.color.fast_md_white_87, ResUtils.getColor(R.color.fast_md_white_87)))
        data.add(ColorResource("White_100", R.color.fast_md_white_100, ResUtils.getColor(R.color.fast_md_white_100)))
        data.add(ColorResource("Red_50", R.color.fast_md_red50, ResUtils.getColor(R.color.fast_md_red50)))
        data.add(ColorResource("Red_100", R.color.fast_md_red100, ResUtils.getColor(R.color.fast_md_red100)))
        data.add(ColorResource("Red_200", R.color.fast_md_red200, ResUtils.getColor(R.color.fast_md_red200)))
        data.add(ColorResource("Red_300", R.color.fast_md_red300, ResUtils.getColor(R.color.fast_md_red300)))
        data.add(ColorResource("Red_400", R.color.fast_md_red400, ResUtils.getColor(R.color.fast_md_red400)))
        data.add(ColorResource("Red_500", R.color.fast_md_red500, ResUtils.getColor(R.color.fast_md_red500)))
        data.add(ColorResource("Red_600", R.color.fast_md_red600, ResUtils.getColor(R.color.fast_md_red600)))
        data.add(ColorResource("Red_700", R.color.fast_md_red700, ResUtils.getColor(R.color.fast_md_red700)))
        data.add(ColorResource("Red_800", R.color.fast_md_red800, ResUtils.getColor(R.color.fast_md_red800)))
        data.add(ColorResource("Red_900", R.color.fast_md_red900, ResUtils.getColor(R.color.fast_md_red900)))
        data.add(ColorResource("Red_A100", R.color.fast_md_redA100, ResUtils.getColor(R.color.fast_md_redA100)))
        data.add(ColorResource("Red_A200", R.color.fast_md_redA200, ResUtils.getColor(R.color.fast_md_redA200)))
        data.add(ColorResource("Red_A400", R.color.fast_md_redA400, ResUtils.getColor(R.color.fast_md_redA400)))
        data.add(ColorResource("Red_A700", R.color.fast_md_redA700, ResUtils.getColor(R.color.fast_md_redA700)))
        data.add(ColorResource("Pink_50", R.color.fast_md_pink50, ResUtils.getColor(R.color.fast_md_pink50)))
        data.add(ColorResource("Pink_100", R.color.fast_md_pink100, ResUtils.getColor(R.color.fast_md_pink100)))
        data.add(ColorResource("Pink_200", R.color.fast_md_pink200, ResUtils.getColor(R.color.fast_md_pink200)))
        data.add(ColorResource("Pink_300", R.color.fast_md_pink300, ResUtils.getColor(R.color.fast_md_pink300)))
        data.add(ColorResource("Pink_400", R.color.fast_md_pink400, ResUtils.getColor(R.color.fast_md_pink400)))
        data.add(ColorResource("Pink_500", R.color.fast_md_pink500, ResUtils.getColor(R.color.fast_md_pink500)))
        data.add(ColorResource("Pink_600", R.color.fast_md_pink600, ResUtils.getColor(R.color.fast_md_pink600)))
        data.add(ColorResource("Pink_700", R.color.fast_md_pink700, ResUtils.getColor(R.color.fast_md_pink700)))
        data.add(ColorResource("Pink_800", R.color.fast_md_pink800, ResUtils.getColor(R.color.fast_md_pink800)))
        data.add(ColorResource("Pink_900", R.color.fast_md_pink900, ResUtils.getColor(R.color.fast_md_pink900)))
        data.add(ColorResource("Pink_A100", R.color.fast_md_pinkA100, ResUtils.getColor(R.color.fast_md_pinkA100)))
        data.add(ColorResource("Pink_A200", R.color.fast_md_pinkA200, ResUtils.getColor(R.color.fast_md_pinkA200)))
        data.add(ColorResource("Pink_A400", R.color.fast_md_pinkA400, ResUtils.getColor(R.color.fast_md_pinkA400)))
        data.add(ColorResource("Pink_A700", R.color.fast_md_pinkA700, ResUtils.getColor(R.color.fast_md_pinkA700)))
        data.add(ColorResource("Purple_50", R.color.fast_md_purple50, ResUtils.getColor(R.color.fast_md_purple50)))
        data.add(ColorResource("Purple_100", R.color.fast_md_purple100, ResUtils.getColor(R.color.fast_md_purple100)))
        data.add(ColorResource("Purple_200", R.color.fast_md_purple200, ResUtils.getColor(R.color.fast_md_purple200)))
        data.add(ColorResource("Purple_300", R.color.fast_md_purple300, ResUtils.getColor(R.color.fast_md_purple300)))
        data.add(ColorResource("Purple_400", R.color.fast_md_purple400, ResUtils.getColor(R.color.fast_md_purple400)))
        data.add(ColorResource("Purple_500", R.color.fast_md_purple500, ResUtils.getColor(R.color.fast_md_purple500)))
        data.add(ColorResource("Purple_600", R.color.fast_md_purple600, ResUtils.getColor(R.color.fast_md_purple600)))
        data.add(ColorResource("Purple_700", R.color.fast_md_purple700, ResUtils.getColor(R.color.fast_md_purple700)))
        data.add(ColorResource("Purple_800", R.color.fast_md_purple800, ResUtils.getColor(R.color.fast_md_purple800)))
        data.add(ColorResource("Purple_900", R.color.fast_md_purple900, ResUtils.getColor(R.color.fast_md_purple900)))
        data.add(ColorResource("Purple_A100", R.color.fast_md_purpleA100, ResUtils.getColor(R.color.fast_md_purpleA100)))
        data.add(ColorResource("Purple_A200", R.color.fast_md_purpleA200, ResUtils.getColor(R.color.fast_md_purpleA200)))
        data.add(ColorResource("Purple_A400", R.color.fast_md_purpleA400, ResUtils.getColor(R.color.fast_md_purpleA400)))
        data.add(ColorResource("Purple_A700", R.color.fast_md_purpleA700, ResUtils.getColor(R.color.fast_md_purpleA700)))
        data.add(ColorResource("DeepPurple_50", R.color.fast_md_deeppurple50, ResUtils.getColor(R.color.fast_md_deeppurple50)))
        data.add(ColorResource("DeepPurple_100", R.color.fast_md_deeppurple100, ResUtils.getColor(R.color.fast_md_deeppurple100)))
        data.add(ColorResource("DeepPurple_200", R.color.fast_md_deeppurple200, ResUtils.getColor(R.color.fast_md_deeppurple200)))
        data.add(ColorResource("DeepPurple_300", R.color.fast_md_deeppurple300, ResUtils.getColor(R.color.fast_md_deeppurple300)))
        data.add(ColorResource("DeepPurple_400", R.color.fast_md_deeppurple400, ResUtils.getColor(R.color.fast_md_deeppurple400)))
        data.add(ColorResource("DeepPurple_500", R.color.fast_md_deeppurple500, ResUtils.getColor(R.color.fast_md_deeppurple500)))
        data.add(ColorResource("DeepPurple_600", R.color.fast_md_deeppurple600, ResUtils.getColor(R.color.fast_md_deeppurple600)))
        data.add(ColorResource("DeepPurple_700", R.color.fast_md_deeppurple700, ResUtils.getColor(R.color.fast_md_deeppurple700)))
        data.add(ColorResource("DeepPurple_800", R.color.fast_md_deeppurple800, ResUtils.getColor(R.color.fast_md_deeppurple800)))
        data.add(ColorResource("DeepPurple_900", R.color.fast_md_deeppurple900, ResUtils.getColor(R.color.fast_md_deeppurple900)))
        data.add(ColorResource("DeepPurple_A100", R.color.fast_md_deeppurpleA100, ResUtils.getColor(R.color.fast_md_deeppurpleA100)))
        data.add(ColorResource("DeepPurple_A200", R.color.fast_md_deeppurpleA200, ResUtils.getColor(R.color.fast_md_deeppurpleA200)))
        data.add(ColorResource("DeepPurple_A400", R.color.fast_md_deeppurpleA400, ResUtils.getColor(R.color.fast_md_deeppurpleA400)))
        data.add(ColorResource("DeepPurple_A700", R.color.fast_md_deeppurpleA700, ResUtils.getColor(R.color.fast_md_deeppurpleA700)))
        data.add(ColorResource("Indigo_50", R.color.fast_md_indigo50, ResUtils.getColor(R.color.fast_md_indigo50)))
        data.add(ColorResource("Indigo_100", R.color.fast_md_indigo100, ResUtils.getColor(R.color.fast_md_indigo100)))
        data.add(ColorResource("Indigo_200", R.color.fast_md_indigo200, ResUtils.getColor(R.color.fast_md_indigo200)))
        data.add(ColorResource("Indigo_300", R.color.fast_md_indigo300, ResUtils.getColor(R.color.fast_md_indigo300)))
        data.add(ColorResource("Indigo_400", R.color.fast_md_indigo400, ResUtils.getColor(R.color.fast_md_indigo400)))
        data.add(ColorResource("Indigo_500", R.color.fast_md_indigo500, ResUtils.getColor(R.color.fast_md_indigo500)))
        data.add(ColorResource("Indigo_600", R.color.fast_md_indigo600, ResUtils.getColor(R.color.fast_md_indigo600)))
        data.add(ColorResource("Indigo_700", R.color.fast_md_indigo700, ResUtils.getColor(R.color.fast_md_indigo700)))
        data.add(ColorResource("Indigo_800", R.color.fast_md_indigo800, ResUtils.getColor(R.color.fast_md_indigo800)))
        data.add(ColorResource("Indigo_900", R.color.fast_md_indigo900, ResUtils.getColor(R.color.fast_md_indigo900)))
        data.add(ColorResource("Indigo_A100", R.color.fast_md_indigoA100, ResUtils.getColor(R.color.fast_md_indigoA100)))
        data.add(ColorResource("Indigo_A200", R.color.fast_md_indigoA200, ResUtils.getColor(R.color.fast_md_indigoA200)))
        data.add(ColorResource("Indigo_A400", R.color.fast_md_indigoA400, ResUtils.getColor(R.color.fast_md_indigoA400)))
        data.add(ColorResource("Indigo_A700", R.color.fast_md_indigoA700, ResUtils.getColor(R.color.fast_md_indigoA700)))
        data.add(ColorResource("Blue_50", R.color.fast_md_blue50, ResUtils.getColor(R.color.fast_md_blue50)))
        data.add(ColorResource("Blue_100", R.color.fast_md_blue100, ResUtils.getColor(R.color.fast_md_blue100)))
        data.add(ColorResource("Blue_200", R.color.fast_md_blue200, ResUtils.getColor(R.color.fast_md_blue200)))
        data.add(ColorResource("Blue_300", R.color.fast_md_blue300, ResUtils.getColor(R.color.fast_md_blue300)))
        data.add(ColorResource("Blue_400", R.color.fast_md_blue400, ResUtils.getColor(R.color.fast_md_blue400)))
        data.add(ColorResource("Blue_500", R.color.fast_md_blue500, ResUtils.getColor(R.color.fast_md_blue500)))
        data.add(ColorResource("Blue_600", R.color.fast_md_blue600, ResUtils.getColor(R.color.fast_md_blue600)))
        data.add(ColorResource("Blue_700", R.color.fast_md_blue700, ResUtils.getColor(R.color.fast_md_blue700)))
        data.add(ColorResource("Blue_800", R.color.fast_md_blue800, ResUtils.getColor(R.color.fast_md_blue800)))
        data.add(ColorResource("Blue_900", R.color.fast_md_blue900, ResUtils.getColor(R.color.fast_md_blue900)))
        data.add(ColorResource("Blue_A100", R.color.fast_md_blueA100, ResUtils.getColor(R.color.fast_md_blueA100)))
        data.add(ColorResource("Blue_A200", R.color.fast_md_blueA200, ResUtils.getColor(R.color.fast_md_blueA200)))
        data.add(ColorResource("Blue_A400", R.color.fast_md_blueA400, ResUtils.getColor(R.color.fast_md_blueA400)))
        data.add(ColorResource("Blue_A700", R.color.fast_md_blueA700, ResUtils.getColor(R.color.fast_md_blueA700)))
        data.add(ColorResource("LightBlue_50", R.color.fast_md_lightblue50, ResUtils.getColor(R.color.fast_md_lightblue50)))
        data.add(ColorResource("LightBlue_100", R.color.fast_md_lightblue100, ResUtils.getColor(R.color.fast_md_lightblue100)))
        data.add(ColorResource("LightBlue_200", R.color.fast_md_lightblue200, ResUtils.getColor(R.color.fast_md_lightblue200)))
        data.add(ColorResource("LightBlue_300", R.color.fast_md_lightblue300, ResUtils.getColor(R.color.fast_md_lightblue300)))
        data.add(ColorResource("LightBlue_400", R.color.fast_md_lightblue400, ResUtils.getColor(R.color.fast_md_lightblue400)))
        data.add(ColorResource("LightBlue_500", R.color.fast_md_lightblue500, ResUtils.getColor(R.color.fast_md_lightblue500)))
        data.add(ColorResource("LightBlue_600", R.color.fast_md_lightblue600, ResUtils.getColor(R.color.fast_md_lightblue600)))
        data.add(ColorResource("LightBlue_700", R.color.fast_md_lightblue700, ResUtils.getColor(R.color.fast_md_lightblue700)))
        data.add(ColorResource("LightBlue_800", R.color.fast_md_lightblue800, ResUtils.getColor(R.color.fast_md_lightblue800)))
        data.add(ColorResource("LightBlue_900", R.color.fast_md_lightblue900, ResUtils.getColor(R.color.fast_md_lightblue900)))
        data.add(ColorResource("LightBlue_A100", R.color.fast_md_lightblueA100, ResUtils.getColor(R.color.fast_md_lightblueA100)))
        data.add(ColorResource("LightBlue_A200", R.color.fast_md_lightblueA200, ResUtils.getColor(R.color.fast_md_lightblueA200)))
        data.add(ColorResource("LightBlue_A400", R.color.fast_md_lightblueA400, ResUtils.getColor(R.color.fast_md_lightblueA400)))
        data.add(ColorResource("LightBlue_A700", R.color.fast_md_lightblueA700, ResUtils.getColor(R.color.fast_md_lightblueA700)))
        data.add(ColorResource("Cyan_50", R.color.fast_md_cyan50, ResUtils.getColor(R.color.fast_md_cyan50)))
        data.add(ColorResource("Cyan_100", R.color.fast_md_cyan100, ResUtils.getColor(R.color.fast_md_cyan100)))
        data.add(ColorResource("Cyan_200", R.color.fast_md_cyan200, ResUtils.getColor(R.color.fast_md_cyan200)))
        data.add(ColorResource("Cyan_300", R.color.fast_md_cyan300, ResUtils.getColor(R.color.fast_md_cyan300)))
        data.add(ColorResource("Cyan_400", R.color.fast_md_cyan400, ResUtils.getColor(R.color.fast_md_cyan400)))
        data.add(ColorResource("Cyan_500", R.color.fast_md_cyan500, ResUtils.getColor(R.color.fast_md_cyan500)))
        data.add(ColorResource("Cyan_600", R.color.fast_md_cyan600, ResUtils.getColor(R.color.fast_md_cyan600)))
        data.add(ColorResource("Cyan_700", R.color.fast_md_cyan700, ResUtils.getColor(R.color.fast_md_cyan700)))
        data.add(ColorResource("Cyan_800", R.color.fast_md_cyan800, ResUtils.getColor(R.color.fast_md_cyan800)))
        data.add(ColorResource("Cyan_900", R.color.fast_md_cyan900, ResUtils.getColor(R.color.fast_md_cyan900)))
        data.add(ColorResource("Cyan_A100", R.color.fast_md_cyanA100, ResUtils.getColor(R.color.fast_md_cyanA100)))
        data.add(ColorResource("Cyan_A200", R.color.fast_md_cyanA200, ResUtils.getColor(R.color.fast_md_cyanA200)))
        data.add(ColorResource("Cyan_A400", R.color.fast_md_cyanA400, ResUtils.getColor(R.color.fast_md_cyanA400)))
        data.add(ColorResource("Cyan_A700", R.color.fast_md_cyanA700, ResUtils.getColor(R.color.fast_md_cyanA700)))
        data.add(ColorResource("Teal_50", R.color.fast_md_teal50, ResUtils.getColor(R.color.fast_md_teal50)))
        data.add(ColorResource("Teal_100", R.color.fast_md_teal100, ResUtils.getColor(R.color.fast_md_teal100)))
        data.add(ColorResource("Teal_200", R.color.fast_md_teal200, ResUtils.getColor(R.color.fast_md_teal200)))
        data.add(ColorResource("Teal_300", R.color.fast_md_teal300, ResUtils.getColor(R.color.fast_md_teal300)))
        data.add(ColorResource("Teal_400", R.color.fast_md_teal400, ResUtils.getColor(R.color.fast_md_teal400)))
        data.add(ColorResource("Teal_500", R.color.fast_md_teal500, ResUtils.getColor(R.color.fast_md_teal500)))
        data.add(ColorResource("Teal_600", R.color.fast_md_teal600, ResUtils.getColor(R.color.fast_md_teal600)))
        data.add(ColorResource("Teal_700", R.color.fast_md_teal700, ResUtils.getColor(R.color.fast_md_teal700)))
        data.add(ColorResource("Teal_800", R.color.fast_md_teal800, ResUtils.getColor(R.color.fast_md_teal800)))
        data.add(ColorResource("Teal_900", R.color.fast_md_teal900, ResUtils.getColor(R.color.fast_md_teal900)))
        data.add(ColorResource("Teal_A100", R.color.fast_md_tealA100, ResUtils.getColor(R.color.fast_md_tealA100)))
        data.add(ColorResource("Teal_A200", R.color.fast_md_tealA200, ResUtils.getColor(R.color.fast_md_tealA200)))
        data.add(ColorResource("Teal_A400", R.color.fast_md_tealA400, ResUtils.getColor(R.color.fast_md_tealA400)))
        data.add(ColorResource("Teal_A700", R.color.fast_md_tealA700, ResUtils.getColor(R.color.fast_md_tealA700)))
        data.add(ColorResource("Green_50", R.color.fast_md_green50, ResUtils.getColor(R.color.fast_md_green50)))
        data.add(ColorResource("Green_100", R.color.fast_md_green100, ResUtils.getColor(R.color.fast_md_green100)))
        data.add(ColorResource("Green_200", R.color.fast_md_green200, ResUtils.getColor(R.color.fast_md_green200)))
        data.add(ColorResource("Green_300", R.color.fast_md_green300, ResUtils.getColor(R.color.fast_md_green300)))
        data.add(ColorResource("Green_400", R.color.fast_md_green400, ResUtils.getColor(R.color.fast_md_green400)))
        data.add(ColorResource("Green_500", R.color.fast_md_green500, ResUtils.getColor(R.color.fast_md_green500)))
        data.add(ColorResource("Green_600", R.color.fast_md_green600, ResUtils.getColor(R.color.fast_md_green600)))
        data.add(ColorResource("Green_700", R.color.fast_md_green700, ResUtils.getColor(R.color.fast_md_green700)))
        data.add(ColorResource("Green_800", R.color.fast_md_green800, ResUtils.getColor(R.color.fast_md_green800)))
        data.add(ColorResource("Green_900", R.color.fast_md_green900, ResUtils.getColor(R.color.fast_md_green900)))
        data.add(ColorResource("Green_A100", R.color.fast_md_greenA100, ResUtils.getColor(R.color.fast_md_greenA100)))
        data.add(ColorResource("Green_A200", R.color.fast_md_greenA200, ResUtils.getColor(R.color.fast_md_greenA200)))
        data.add(ColorResource("Green_A400", R.color.fast_md_greenA400, ResUtils.getColor(R.color.fast_md_greenA400)))
        data.add(ColorResource("Green_A700", R.color.fast_md_greenA700, ResUtils.getColor(R.color.fast_md_greenA700)))
        data.add(ColorResource("LightGreen_50", R.color.fast_md_lightgreen50, ResUtils.getColor(R.color.fast_md_lightgreen50)))
        data.add(ColorResource("LightGreen_100", R.color.fast_md_lightgreen100, ResUtils.getColor(R.color.fast_md_lightgreen100)))
        data.add(ColorResource("LightGreen_200", R.color.fast_md_lightgreen200, ResUtils.getColor(R.color.fast_md_lightgreen200)))
        data.add(ColorResource("LightGreen_300", R.color.fast_md_lightgreen300, ResUtils.getColor(R.color.fast_md_lightgreen300)))
        data.add(ColorResource("LightGreen_400", R.color.fast_md_lightgreen400, ResUtils.getColor(R.color.fast_md_lightgreen400)))
        data.add(ColorResource("LightGreen_500", R.color.fast_md_lightgreen500, ResUtils.getColor(R.color.fast_md_lightgreen500)))
        data.add(ColorResource("LightGreen_600", R.color.fast_md_lightgreen600, ResUtils.getColor(R.color.fast_md_lightgreen600)))
        data.add(ColorResource("LightGreen_700", R.color.fast_md_lightgreen700, ResUtils.getColor(R.color.fast_md_lightgreen700)))
        data.add(ColorResource("LightGreen_800", R.color.fast_md_lightgreen800, ResUtils.getColor(R.color.fast_md_lightgreen800)))
        data.add(ColorResource("LightGreen_900", R.color.fast_md_lightgreen900, ResUtils.getColor(R.color.fast_md_lightgreen900)))
        data.add(ColorResource("LightGreen_A100", R.color.fast_md_lightgreenA100, ResUtils.getColor(R.color.fast_md_lightgreenA100)))
        data.add(ColorResource("LightGreen_A200", R.color.fast_md_lightgreenA200, ResUtils.getColor(R.color.fast_md_lightgreenA200)))
        data.add(ColorResource("LightGreen_A400", R.color.fast_md_lightgreenA400, ResUtils.getColor(R.color.fast_md_lightgreenA400)))
        data.add(ColorResource("LightGreen_A700", R.color.fast_md_lightgreenA700, ResUtils.getColor(R.color.fast_md_lightgreenA700)))
        data.add(ColorResource("Lime_50", R.color.fast_md_lime50, ResUtils.getColor(R.color.fast_md_lime50)))
        data.add(ColorResource("Lime_100", R.color.fast_md_lime100, ResUtils.getColor(R.color.fast_md_lime100)))
        data.add(ColorResource("Lime_200", R.color.fast_md_lime200, ResUtils.getColor(R.color.fast_md_lime200)))
        data.add(ColorResource("Lime_300", R.color.fast_md_lime300, ResUtils.getColor(R.color.fast_md_lime300)))
        data.add(ColorResource("Lime_400", R.color.fast_md_lime400, ResUtils.getColor(R.color.fast_md_lime400)))
        data.add(ColorResource("Lime_500", R.color.fast_md_lime500, ResUtils.getColor(R.color.fast_md_lime500)))
        data.add(ColorResource("Lime_600", R.color.fast_md_lime600, ResUtils.getColor(R.color.fast_md_lime600)))
        data.add(ColorResource("Lime_700", R.color.fast_md_lime700, ResUtils.getColor(R.color.fast_md_lime700)))
        data.add(ColorResource("Lime_800", R.color.fast_md_lime800, ResUtils.getColor(R.color.fast_md_lime800)))
        data.add(ColorResource("Lime_900", R.color.fast_md_lime900, ResUtils.getColor(R.color.fast_md_lime900)))
        data.add(ColorResource("Lime_A100", R.color.fast_md_limeA100, ResUtils.getColor(R.color.fast_md_limeA100)))
        data.add(ColorResource("Lime_A200", R.color.fast_md_limeA200, ResUtils.getColor(R.color.fast_md_limeA200)))
        data.add(ColorResource("Lime_A400", R.color.fast_md_limeA400, ResUtils.getColor(R.color.fast_md_limeA400)))
        data.add(ColorResource("Lime_A700", R.color.fast_md_limeA700, ResUtils.getColor(R.color.fast_md_limeA700)))
        data.add(ColorResource("Yellow_50", R.color.fast_md_yellow50, ResUtils.getColor(R.color.fast_md_yellow50)))
        data.add(ColorResource("Yellow_100", R.color.fast_md_yellow100, ResUtils.getColor(R.color.fast_md_yellow100)))
        data.add(ColorResource("Yellow_200", R.color.fast_md_yellow200, ResUtils.getColor(R.color.fast_md_yellow200)))
        data.add(ColorResource("Yellow_300", R.color.fast_md_yellow300, ResUtils.getColor(R.color.fast_md_yellow300)))
        data.add(ColorResource("Yellow_400", R.color.fast_md_yellow400, ResUtils.getColor(R.color.fast_md_yellow400)))
        data.add(ColorResource("Yellow_500", R.color.fast_md_yellow500, ResUtils.getColor(R.color.fast_md_yellow500)))
        data.add(ColorResource("Yellow_600", R.color.fast_md_yellow600, ResUtils.getColor(R.color.fast_md_yellow600)))
        data.add(ColorResource("Yellow_700", R.color.fast_md_yellow700, ResUtils.getColor(R.color.fast_md_yellow700)))
        data.add(ColorResource("Yellow_800", R.color.fast_md_yellow800, ResUtils.getColor(R.color.fast_md_yellow800)))
        data.add(ColorResource("Yellow_900", R.color.fast_md_yellow900, ResUtils.getColor(R.color.fast_md_yellow900)))
        data.add(ColorResource("Yellow_A100", R.color.fast_md_yellowA100, ResUtils.getColor(R.color.fast_md_yellowA100)))
        data.add(ColorResource("Yellow_A200", R.color.fast_md_yellowA200, ResUtils.getColor(R.color.fast_md_yellowA200)))
        data.add(ColorResource("Yellow_A400", R.color.fast_md_yellowA400, ResUtils.getColor(R.color.fast_md_yellowA400)))
        data.add(ColorResource("Yellow_A700", R.color.fast_md_yellowA700, ResUtils.getColor(R.color.fast_md_yellowA700)))
        data.add(ColorResource("Amber_50", R.color.fast_md_amber50, ResUtils.getColor(R.color.fast_md_amber50)))
        data.add(ColorResource("Amber_100", R.color.fast_md_amber100, ResUtils.getColor(R.color.fast_md_amber100)))
        data.add(ColorResource("Amber_200", R.color.fast_md_amber200, ResUtils.getColor(R.color.fast_md_amber200)))
        data.add(ColorResource("Amber_300", R.color.fast_md_amber300, ResUtils.getColor(R.color.fast_md_amber300)))
        data.add(ColorResource("Amber_400", R.color.fast_md_amber400, ResUtils.getColor(R.color.fast_md_amber400)))
        data.add(ColorResource("Amber_500", R.color.fast_md_amber500, ResUtils.getColor(R.color.fast_md_amber500)))
        data.add(ColorResource("Amber_600", R.color.fast_md_amber600, ResUtils.getColor(R.color.fast_md_amber600)))
        data.add(ColorResource("Amber_700", R.color.fast_md_amber700, ResUtils.getColor(R.color.fast_md_amber700)))
        data.add(ColorResource("Amber_800", R.color.fast_md_amber800, ResUtils.getColor(R.color.fast_md_amber800)))
        data.add(ColorResource("Amber_900", R.color.fast_md_amber900, ResUtils.getColor(R.color.fast_md_amber900)))
        data.add(ColorResource("Amber_A100", R.color.fast_md_amberA100, ResUtils.getColor(R.color.fast_md_amberA100)))
        data.add(ColorResource("Amber_A200", R.color.fast_md_amberA200, ResUtils.getColor(R.color.fast_md_amberA200)))
        data.add(ColorResource("Amber_A400", R.color.fast_md_amberA400, ResUtils.getColor(R.color.fast_md_amberA400)))
        data.add(ColorResource("Amber_A700", R.color.fast_md_amberA700, ResUtils.getColor(R.color.fast_md_amberA700)))
        data.add(ColorResource("Orange_50", R.color.fast_md_orange50, ResUtils.getColor(R.color.fast_md_orange50)))
        data.add(ColorResource("Orange_100", R.color.fast_md_orange100, ResUtils.getColor(R.color.fast_md_orange100)))
        data.add(ColorResource("Orange_200", R.color.fast_md_orange200, ResUtils.getColor(R.color.fast_md_orange200)))
        data.add(ColorResource("Orange_300", R.color.fast_md_orange300, ResUtils.getColor(R.color.fast_md_orange300)))
        data.add(ColorResource("Orange_400", R.color.fast_md_orange400, ResUtils.getColor(R.color.fast_md_orange400)))
        data.add(ColorResource("Orange_500", R.color.fast_md_orange500, ResUtils.getColor(R.color.fast_md_orange500)))
        data.add(ColorResource("Orange_600", R.color.fast_md_orange600, ResUtils.getColor(R.color.fast_md_orange600)))
        data.add(ColorResource("Orange_700", R.color.fast_md_orange700, ResUtils.getColor(R.color.fast_md_orange700)))
        data.add(ColorResource("Orange_800", R.color.fast_md_orange800, ResUtils.getColor(R.color.fast_md_orange800)))
        data.add(ColorResource("Orange_900", R.color.fast_md_orange900, ResUtils.getColor(R.color.fast_md_orange900)))
        data.add(ColorResource("Orange_A100", R.color.fast_md_orangeA100, ResUtils.getColor(R.color.fast_md_orangeA100)))
        data.add(ColorResource("Orange_A200", R.color.fast_md_orangeA200, ResUtils.getColor(R.color.fast_md_orangeA200)))
        data.add(ColorResource("Orange_A400", R.color.fast_md_orangeA400, ResUtils.getColor(R.color.fast_md_orangeA400)))
        data.add(ColorResource("Orange_A700", R.color.fast_md_orangeA700, ResUtils.getColor(R.color.fast_md_orangeA700)))
        data.add(ColorResource("DeepOrange_50", R.color.fast_md_deeporange50, ResUtils.getColor(R.color.fast_md_deeporange50)))
        data.add(ColorResource("DeepOrange_100", R.color.fast_md_deeporange100, ResUtils.getColor(R.color.fast_md_deeporange100)))
        data.add(ColorResource("DeepOrange_200", R.color.fast_md_deeporange200, ResUtils.getColor(R.color.fast_md_deeporange200)))
        data.add(ColorResource("DeepOrange_300", R.color.fast_md_deeporange300, ResUtils.getColor(R.color.fast_md_deeporange300)))
        data.add(ColorResource("DeepOrange_400", R.color.fast_md_deeporange400, ResUtils.getColor(R.color.fast_md_deeporange400)))
        data.add(ColorResource("DeepOrange_500", R.color.fast_md_deeporange500, ResUtils.getColor(R.color.fast_md_deeporange500)))
        data.add(ColorResource("DeepOrange_600", R.color.fast_md_deeporange600, ResUtils.getColor(R.color.fast_md_deeporange600)))
        data.add(ColorResource("DeepOrange_700", R.color.fast_md_deeporange700, ResUtils.getColor(R.color.fast_md_deeporange700)))
        data.add(ColorResource("DeepOrange_800", R.color.fast_md_deeporange800, ResUtils.getColor(R.color.fast_md_deeporange800)))
        data.add(ColorResource("DeepOrange_900", R.color.fast_md_deeporange900, ResUtils.getColor(R.color.fast_md_deeporange900)))
        data.add(ColorResource("DeepOrange_A100", R.color.fast_md_deeporangeA100, ResUtils.getColor(R.color.fast_md_deeporangeA100)))
        data.add(ColorResource("DeepOrange_A200", R.color.fast_md_deeporangeA200, ResUtils.getColor(R.color.fast_md_deeporangeA200)))
        data.add(ColorResource("DeepOrange_A400", R.color.fast_md_deeporangeA400, ResUtils.getColor(R.color.fast_md_deeporangeA400)))
        data.add(ColorResource("DeepOrange_A700", R.color.fast_md_deeporangeA700, ResUtils.getColor(R.color.fast_md_deeporangeA700)))
        data.add(ColorResource("Brown_50", R.color.fast_md_brown50, ResUtils.getColor(R.color.fast_md_brown50)))
        data.add(ColorResource("Brown_100", R.color.fast_md_brown100, ResUtils.getColor(R.color.fast_md_brown100)))
        data.add(ColorResource("Brown_200", R.color.fast_md_brown200, ResUtils.getColor(R.color.fast_md_brown200)))
        data.add(ColorResource("Brown_300", R.color.fast_md_brown300, ResUtils.getColor(R.color.fast_md_brown300)))
        data.add(ColorResource("Brown_400", R.color.fast_md_brown400, ResUtils.getColor(R.color.fast_md_brown400)))
        data.add(ColorResource("Brown_500", R.color.fast_md_brown500, ResUtils.getColor(R.color.fast_md_brown500)))
        data.add(ColorResource("Brown_600", R.color.fast_md_brown600, ResUtils.getColor(R.color.fast_md_brown600)))
        data.add(ColorResource("Brown_700", R.color.fast_md_brown700, ResUtils.getColor(R.color.fast_md_brown700)))
        data.add(ColorResource("Brown_800", R.color.fast_md_brown800, ResUtils.getColor(R.color.fast_md_brown800)))
        data.add(ColorResource("Brown_900", R.color.fast_md_brown900, ResUtils.getColor(R.color.fast_md_brown900)))
        data.add(ColorResource("Grey_50", R.color.fast_md_grey50, ResUtils.getColor(R.color.fast_md_grey50)))
        data.add(ColorResource("Grey_100", R.color.fast_md_grey100, ResUtils.getColor(R.color.fast_md_grey100)))
        data.add(ColorResource("Grey_200", R.color.fast_md_grey200, ResUtils.getColor(R.color.fast_md_grey200)))
        data.add(ColorResource("Grey_300", R.color.fast_md_grey300, ResUtils.getColor(R.color.fast_md_grey300)))
        data.add(ColorResource("Grey_400", R.color.fast_md_grey400, ResUtils.getColor(R.color.fast_md_grey400)))
        data.add(ColorResource("Grey_500", R.color.fast_md_grey500, ResUtils.getColor(R.color.fast_md_grey500)))
        data.add(ColorResource("Grey_600", R.color.fast_md_grey600, ResUtils.getColor(R.color.fast_md_grey600)))
        data.add(ColorResource("Grey_700", R.color.fast_md_grey700, ResUtils.getColor(R.color.fast_md_grey700)))
        data.add(ColorResource("Grey_800", R.color.fast_md_grey800, ResUtils.getColor(R.color.fast_md_grey800)))
        data.add(ColorResource("Grey_900", R.color.fast_md_grey900, ResUtils.getColor(R.color.fast_md_grey900)))
        data.add(ColorResource("BlueGrey_50", R.color.fast_md_bluegrey50, ResUtils.getColor(R.color.fast_md_bluegrey50)))
        data.add(ColorResource("BlueGrey_100", R.color.fast_md_bluegrey100, ResUtils.getColor(R.color.fast_md_bluegrey100)))
        data.add(ColorResource("BlueGrey_200", R.color.fast_md_bluegrey200, ResUtils.getColor(R.color.fast_md_bluegrey200)))
        data.add(ColorResource("BlueGrey_300", R.color.fast_md_bluegrey300, ResUtils.getColor(R.color.fast_md_bluegrey300)))
        data.add(ColorResource("BlueGrey_400", R.color.fast_md_bluegrey400, ResUtils.getColor(R.color.fast_md_bluegrey400)))
        data.add(ColorResource("BlueGrey_500", R.color.fast_md_bluegrey500, ResUtils.getColor(R.color.fast_md_bluegrey500)))
        data.add(ColorResource("BlueGrey_600", R.color.fast_md_bluegrey600, ResUtils.getColor(R.color.fast_md_bluegrey600)))
        data.add(ColorResource("BlueGrey_700", R.color.fast_md_bluegrey700, ResUtils.getColor(R.color.fast_md_bluegrey700)))
        data.add(ColorResource("BlueGrey_800", R.color.fast_md_bluegrey800, ResUtils.getColor(R.color.fast_md_bluegrey800)))
        data.add(ColorResource("BlueGrey_900", R.color.fast_md_bluegrey900, ResUtils.getColor(R.color.fast_md_bluegrey900)))

        val filterDelegate = FilterDelegate(filterButton) { data: List<Any> ->
            viewDelegate.setData(data)
        }

        filterDelegate.sortEntries = false

        filterDelegate.updateResources(data)
    }

    fun setOnColorSelectedListener(callback: (ColorResource)->Unit)
    {
        listener = callback
    }
}